config/routes.rb
Rails.application.routes.draw do
  root :to => 'posts#index'

  resources :posts do
    resources :comments, :except => [:show, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post


end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  validates :title, :presence => true
  validates :body, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      render :new
    end
  end
  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@comment.post)
  end
  private
  def comment_params
    params.require(:comment).permit(:user, :reply)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    render :index
  end
  def show
    @post = Post.find(params[:id])
    render :show
  end
  def new
    @post = Post.new
    render :new
  end
  def create
    @post = Post.new (post_params)
    if @post.save
      flash[:notice] = "Post has been added."
      redirect_to posts_path
    else
      render :new
    end
  end
  def edit
    @post = Post.find(params[:id])
    render :edit
  end
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  private
  def post_params
    params.require(:post).permit(:title, :category, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= render('layouts/errors', :object => @comment) %>

<%= form_for [@post, @comment] do |f| %>
  <%= f.label :user %>
  <%= f.text_field :user %>
  <%= f.label :reply %>
  <%= f.text_field :reply, size: "100x100" %>
  <p><%= f.submit %></p>
<% end %>

app/views/comments/new.html.erb
<h1>New comment for <%= @post.title %></h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= flash[:notice] %>
      <%= flash[:alert] %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>


<%= form_for [@post] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, size: "50x50" %>
  <br>
  <%= f.label :category %>
  <%= f.text_field :category, size: "50x50" %>
  <br>
  <%= f.label :body %>
  <%= f.text_field :body, size: "100x100" %>
  <br>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form" %>




<h5><%= link_to "Back to HQ", posts_path %></h5>

app/views/posts/index.html.erb
<h1>Squad Posts</h1>


<hr>
<ul>
  <% @posts.each do |post| %>

  <h1><%= link_to post.title, post_path(post)%></h1>
  <ul>
    <li>Category: <br> <%= post.category %></li>

    <li>Time created: <br> <%= post.created_at %></li>
  </ul>
  <hr>
  <% end %>

</ul>
<%= link_to "New Post", new_post_path %>

app/views/posts/new.html.erb
<% content_for(:title, "New Post | Squad") %>


<h1>New Post</h1>

<%= render "form" %>


<h5><%= link_to "Back to HQ", posts_path %></h5>

app/views/posts/show.html.erb
<% content_for(:title, "Post | Squad") %>

<h1><%= @post.title %></h1>
<h2><%= @post.category %></h2>
<h3><%= @post.body %></h3>
<h4><%= @post.created_at %></h4>
<br>
<p><%= link_to "Edit", edit_post_path(@post) %> |
<%= link_to "Delete", post_path(@post),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>
<hr>
<% if @post.comments.any? %>
  <h4>Here are the comments for this post:</h4>

  <ul>
    <% @post.comments.each do |comment| %>
      <li>
        <%= comment.reply %> |
        <br>
        <%= link_to "Edit", edit_post_comment_path(@post, comment) %> |
        <%= link_to "Delete", post_comment_path(@post, comment),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
                                            <hr>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no comments yet!</p>
<% end %>
<p><%= link_to "Add a comment", new_post_comment_path(@post) %></p>


<hr>
<br>
<h3><%= link_to "Back to HQ", posts_path %></h3>